### ISSUE TITLE
Why highpass filter with 1Hz?

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-biomag-group-demo#15]
If this pipeline basically studies evoked potentials (with MNE and beamforming), isn't the 1Hz highpass filter problematic? Yes, it gets rid of the 'fanning', but it will severely distort the ERP/ERF as well. I know some reviewers (and sometimes I'm one of them) who will reject a paper for using a highpass filter over 0.5Hz for a study that interprets evoked potentials.

See also:

Tanner, D., Morgan-Short, K., & Luck, S. J. (2015). How inappropriate high-pass filters can produce artifactual effects and incorrect conclusions in ERP studies of language and cognition. Psychophysiology, 52(8), 997–1009. http://doi.org/10.1111/psyp.12437

**Comment by agramfort** [comment]
we checked that the early evoked components are not clearly distorted by
our filters:

http://mne-tools.github.io/mne-biomag-group-demo/_images/sphx_glr_plot_group_001.png

ok?

**Comment by wmvanvliet** [comment]
Yes, the results look fine in this case. But generally, you don't want to advocate highpassing with 1Hz for evoked analysis. My concern is that this code is going to be used as a template for future analyses by young promising researchers. Of course, you probably explain filtering in more detail in the manuscript, but I really don't want people to think: "highpassing with 1Hz is in general a valid alternative to using a baseline and good for getting rid of 'fanning'". In many cases, this filter will remove evoked effects (such as the N400). In these cases, tSSS is a better option if available (although I'm aware that it has its own problems). I wonder how the authors of FieldTrip and SPM will approach the filtering on this dataset.

**Comment by jasmainak** [comment]
You are right that using these scripts as a template can be a recipe for disaster. We agreed with @dengemann the other day that we will advocate against such an approach. It is more about equipping the readers/users with the right tools to perform group analysis: visualization, reports etc., and to be aware of the various options out there implemented in MNE. Perhaps we can clarify this more explicitly in the documentation.

**Comment by agramfort** [comment]
note that in our WIP manuscript we also compare with tSSS
