### ISSUE TITLE
Please clean/rebase the repo

### ISSUE THREAD

**Issue by danieltomasz** [mne-tools/mne-biomag-group-demo#33]
The repo contain nearly 1gb hidden git objects (probably you have some output  data stored in history). Some people who read your paper and want to do your analyses and want to pull your repo could prefer reduced size :). Anyway, great job with paper and tutorial!

**Comment by jasmainak** [comment]
arggh ... you are right. It's probably the `gh-pages` branch which hosts the website. We could squash the commits there. Okay with you @agramfort @larsoner ?

**Comment by larsoner** [comment]
Yes feel free to squash. 

In the meantime @danieltomasz you can use this to get just `master` and ignore `gh-pages`:

https://stackoverflow.com/questions/1911109/how-to-clone-a-specific-git-branch#answer-4568323

**Comment by danieltomasz** [comment]
Now it makes sense, 1000+ images takes space :)

**Comment by jasmainak** [comment]
okay it should be fixed now :) Thanks for reporting @danieltomasz !
