### ISSUE TITLE
UnavailableInvalidChannel: The channel is not accessible or is invalid. clinicalgraphics

### ISSUE THREAD

**Issue by levchenkoegor** [mne-tools/mne-biomag-group-demo#39]
Hi everyone!

Thank you for that amazing tutorial and pipeline!
I tried to reproduce your code but faced with the problem at the step of building the conda environment:

```
conda env create -f scripts/environment.yml

Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: clinicalgraphics
  channel url: https://conda.anaconda.org/clinicalgraphics
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

OS: Scientific Linux 7.9, 64-bit
conda version: 4.9.2

Do you have any ideas on how to solve it?
Any ideas are appreciated!

**Comment by wmvanvliet** [comment]
That `environment.yml` file is pretty old by now. Could you try using the newest MNE-Python one?

```
$ curl --remote-name https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
$ conda env update --file environment.yml
```

**Comment by levchenkoegor** [comment]
Thank you!

Looks like the newest MNE-Python is not full for this repo, I just added several packages manually and it works:

```
...
- autoreject
- sphinx-gallery
- sphinx_bootstrap_theme
```

**Comment by agramfort** [comment]
note that we have now moved our effort to
https://mne.tools/mne-bids-pipeline/

to replicate this analysis on any BIDS compatible dataset

>
