### ISSUE TITLE
fix version

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-biomag-group-demo#7]
reminder for myself
https://github.com/mne-tools/mne-biomag-group-demo/blob/388ebe6c3f85c93a2598ca2115e14140963e2175/scripts/results/plot_filter.py#L109

**Comment by larsoner** [comment]
What needs to change here?

**Comment by jasmainak** [comment]
I thought 0.16 is not yet released?

**Comment by larsoner** [comment]
It's not, but it will be the default when it's released. So it's fine to write `0.16+` or `≥ 0.16`.

**Comment by jasmainak** [comment]
okay I see. We can close the issue then
