### ISSUE TITLE
Anatomy for subject 19

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-biomag-group-demo#8]
How do I run the anatomy for subject 19? The comment in the code gives some hint about running `mri_convert`, but could someone explain in more detail?

**Comment by jasmainak** [comment]
yeah I am not sure about `mri_convert`. I think @agramfort can shed more light.

But basically there was a corrupted file in subject 19. Me and @jaeilepp solved it using [this script](https://github.com/mne-tools/mne-biomag-group-demo/commit/3aedc2569c85d75d2dbb31e6426a37e4261333b3). I'm not sure maybe `mri_convert` does the same ...

**Comment by agramfort** [comment]
yes you need to hack the header or use the new bids nii files

btw @jasmainak it would be ideal to have our scripts now use the bids
formated version of this dataset.

**Comment by jasmainak** [comment]
yeah that's a good idea! I'll look into it

**Comment by wmvanvliet** [comment]
tnx!
