### ISSUE TITLE
example for converting ds000117 to bids compatible format

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-biomag-group-demo#9]
see: https://github.com/INCF/BIDS-examples/tree/bep008_meg/ds000117

and https://openfmri.org/dataset/ds000117/

@teonbrooks would you be able to download the dataset from openfmri before the sprint? Thanks!

**Comment by jasmainak** [comment]
oops, sorry wrong repo

**Comment by agramfort** [comment]
if you could use git annex or datalad to fetch the BIDS data it would be
great as we could easily track data changes and derivatives.

**Comment by jasmainak** [comment]
good point indeed
